import type { ColorTheme } from "./index";

export const lightTheme: ColorTheme = {
  directory: { bg: "#ff6b47", fg: "#ffffff" },
  git: { bg: "#4fb3d9", fg: "#ffffff" },
  model: { bg: "#87ceeb", fg: "#000000" },
  session: { bg: "#da70d6", fg: "#ffffff" },
  block: { bg: "#6366f1", fg: "#ffffff" },
  today: { bg: "#10b981", fg: "#ffffff" },
  tmux: { bg: "#32cd32", fg: "#ffffff" },
  context: { bg: "#718096", fg: "#ffffff" },
  contextWarning: { bg: "#d97706", fg: "#ffffff" },
  contextCritical: { bg: "#dc2626", fg: "#ffffff" },
  metrics: { bg: "#6b7280", fg: "#ffffff" },
  version: { bg: "#8b7dd8", fg: "#ffffff" },
  stronkAgentsModeActive: { bg: "#ec4899", fg: "#ffffff" },
  stronkAgentsModeInactive: { bg: "#9ca3af", fg: "#4b5563" },
  stronkAgentsRalphActive: { bg: "#3b82f6", fg: "#ffffff" },
  stronkAgentsRalphWarn: { bg: "#f59e0b", fg: "#000000" },
  stronkAgentsRalphMax: { bg: "#ef4444", fg: "#ffffff" },
  stronkAgentsRalphInactive: { bg: "#9ca3af", fg: "#4b5563" },
  stronkAgentsAgentsActive: { bg: "#8b5cf6", fg: "#ffffff" },
  stronkAgentsAgentsInactive: { bg: "#9ca3af", fg: "#4b5563" },
  stronkAgentsSkillActive: { bg: "#0891b2", fg: "#ffffff" },   // cyan-600
  stronkAgentsSkillInactive: { bg: "#e5e7eb", fg: "#6b7280" },
  stronkAgentsAgentOpus: { bg: "#ffffff", fg: "#ff1493" },
  stronkAgentsAgentSonnet: { bg: "#ffffff", fg: "#795e26" },
  stronkAgentsAgentHaiku: { bg: "#ffffff", fg: "#008000" },
  costNormal: { bg: "#15803d", fg: "#ffffff" },
  costWarning: { bg: "#a16207", fg: "#ffffff" },
  costCritical: { bg: "#b91c1c", fg: "#ffffff" },
};

export const lightAnsi256Theme: ColorTheme = {
  directory: { bg: "#ff5f5f", fg: "#ffffff" },
  git: { bg: "#5fafff", fg: "#ffffff" },
  model: { bg: "#87d7ff", fg: "#000000" },
  session: { bg: "#ff5fff", fg: "#ffffff" },
  block: { bg: "#5f5fff", fg: "#ffffff" },
  today: { bg: "#00d787", fg: "#ffffff" },
  tmux: { bg: "#00ff5f", fg: "#ffffff" },
  context: { bg: "#808080", fg: "#ffffff" },
  contextWarning: { bg: "#d78700", fg: "#ffffff" },
  contextCritical: { bg: "#d70000", fg: "#ffffff" },
  metrics: { bg: "#767676", fg: "#ffffff" },
  version: { bg: "#af87ff", fg: "#ffffff" },
  stronkAgentsModeActive: { bg: "#ff5fd7", fg: "#ffffff" },
  stronkAgentsModeInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsRalphActive: { bg: "#5f87ff", fg: "#ffffff" },
  stronkAgentsRalphWarn: { bg: "#ffaf00", fg: "#000000" },
  stronkAgentsRalphMax: { bg: "#ff5f5f", fg: "#ffffff" },
  stronkAgentsRalphInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsAgentsActive: { bg: "#875fff", fg: "#ffffff" },
  stronkAgentsAgentsInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsSkillActive: { bg: "#00afaf", fg: "#ffffff" },
  stronkAgentsSkillInactive: { bg: "#d0d0d0", fg: "#767676" },
  stronkAgentsAgentOpus: { bg: "#ffffff", fg: "#ff5f87" },
  stronkAgentsAgentSonnet: { bg: "#ffffff", fg: "#af8700" },
  stronkAgentsAgentHaiku: { bg: "#ffffff", fg: "#008700" },
  costNormal: { bg: "#15803d", fg: "#ffffff" },
  costWarning: { bg: "#a16207", fg: "#ffffff" },
  costCritical: { bg: "#b91c1c", fg: "#ffffff" },
};

export const lightAnsiTheme: ColorTheme = {
  directory: { bg: "#ff5f5f", fg: "#ffffff" },
  git: { bg: "#5fafff", fg: "#ffffff" },
  model: { bg: "#87d7ff", fg: "#000000" },
  session: { bg: "#ff5fff", fg: "#ffffff" },
  block: { bg: "#5f5fff", fg: "#ffffff" },
  today: { bg: "#00d787", fg: "#ffffff" },
  tmux: { bg: "#00ff5f", fg: "#ffffff" },
  context: { bg: "#808080", fg: "#ffffff" },
  contextWarning: { bg: "#d78700", fg: "#ffffff" },
  contextCritical: { bg: "#d70000", fg: "#ffffff" },
  metrics: { bg: "#767676", fg: "#ffffff" },
  version: { bg: "#af87ff", fg: "#ffffff" },
  stronkAgentsModeActive: { bg: "#ff5fd7", fg: "#ffffff" },
  stronkAgentsModeInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsRalphActive: { bg: "#5f87ff", fg: "#ffffff" },
  stronkAgentsRalphWarn: { bg: "#ffaf00", fg: "#000000" },
  stronkAgentsRalphMax: { bg: "#ff5f5f", fg: "#ffffff" },
  stronkAgentsRalphInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsAgentsActive: { bg: "#875fff", fg: "#ffffff" },
  stronkAgentsAgentsInactive: { bg: "#a8a8a8", fg: "#585858" },
  stronkAgentsSkillActive: { bg: "#00afaf", fg: "#ffffff" },
  stronkAgentsSkillInactive: { bg: "#d0d0d0", fg: "#767676" },
  stronkAgentsAgentOpus: { bg: "#ffffff", fg: "#ff0000" },
  stronkAgentsAgentSonnet: { bg: "#ffffff", fg: "#ffaf00" },
  stronkAgentsAgentHaiku: { bg: "#ffffff", fg: "#00ff00" },
  costNormal: { bg: "#15803d", fg: "#ffffff" },
  costWarning: { bg: "#a16207", fg: "#ffffff" },
  costCritical: { bg: "#b91c1c", fg: "#ffffff" },
};
